package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Mechanic;
import org.mybatis.cdi.Mapper;

@Mapper
public interface MechanicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MECHANIC
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MECHANIC
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    int insert(Mechanic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MECHANIC
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    Mechanic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MECHANIC
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    List<Mechanic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MECHANIC
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    int updateByPrimaryKey(Mechanic record);
}