package lt.vu.mybatis.model;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.BRAND
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MODEL
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MECHANIC_ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    private Integer mechanicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.CARS_ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    private Integer carsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.BRAND
     *
     * @return the value of PUBLIC.CAR.BRAND
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.BRAND
     *
     * @param brand the value for PUBLIC.CAR.BRAND
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MODEL
     *
     * @return the value of PUBLIC.CAR.MODEL
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MODEL
     *
     * @param model the value for PUBLIC.CAR.MODEL
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MECHANIC_ID
     *
     * @return the value of PUBLIC.CAR.MECHANIC_ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public Integer getMechanicId() {
        return mechanicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MECHANIC_ID
     *
     * @param mechanicId the value for PUBLIC.CAR.MECHANIC_ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public void setMechanicId(Integer mechanicId) {
        this.mechanicId = mechanicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.CARS_ID
     *
     * @return the value of PUBLIC.CAR.CARS_ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public Integer getCarsId() {
        return carsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.CARS_ID
     *
     * @param carsId the value for PUBLIC.CAR.CARS_ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public void setCarsId(Integer carsId) {
        this.carsId = carsId;
    }
}