package lt.vu.mybatis.model;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MAKE
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    private String make;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MODEL
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MECHANIC_ID
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    private Integer mechanicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.CARS_ID
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    private Integer carsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MAKE
     *
     * @return the value of PUBLIC.CAR.MAKE
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    public String getMake() {
        return make;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MAKE
     *
     * @param make the value for PUBLIC.CAR.MAKE
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    public void setMake(String make) {
        this.make = make;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MODEL
     *
     * @return the value of PUBLIC.CAR.MODEL
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MODEL
     *
     * @param model the value for PUBLIC.CAR.MODEL
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MECHANIC_ID
     *
     * @return the value of PUBLIC.CAR.MECHANIC_ID
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    public Integer getMechanicId() {
        return mechanicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MECHANIC_ID
     *
     * @param mechanicId the value for PUBLIC.CAR.MECHANIC_ID
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    public void setMechanicId(Integer mechanicId) {
        this.mechanicId = mechanicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.CARS_ID
     *
     * @return the value of PUBLIC.CAR.CARS_ID
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    public Integer getCarsId() {
        return carsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.CARS_ID
     *
     * @param carsId the value for PUBLIC.CAR.CARS_ID
     *
     * @mbg.generated Tue Mar 02 17:20:50 EET 2021
     */
    public void setCarsId(Integer carsId) {
        this.carsId = carsId;
    }
}