package lt.vu.mybatis.model;

public class Mechanic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MECHANIC.ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MECHANIC.NAME
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MECHANIC.SERVICE_ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    private Integer serviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MECHANIC.ID
     *
     * @return the value of PUBLIC.MECHANIC.ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MECHANIC.ID
     *
     * @param id the value for PUBLIC.MECHANIC.ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MECHANIC.NAME
     *
     * @return the value of PUBLIC.MECHANIC.NAME
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MECHANIC.NAME
     *
     * @param name the value for PUBLIC.MECHANIC.NAME
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MECHANIC.SERVICE_ID
     *
     * @return the value of PUBLIC.MECHANIC.SERVICE_ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MECHANIC.SERVICE_ID
     *
     * @param serviceId the value for PUBLIC.MECHANIC.SERVICE_ID
     *
     * @mbg.generated Mon Mar 08 22:25:25 EET 2021
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }
}