package lt.vu.mybatis.model;

public class Service {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SERVICE.ID
     *
     * @mbg.generated Wed Mar 10 20:42:44 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SERVICE.NAME
     *
     * @mbg.generated Wed Mar 10 20:42:44 EET 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SERVICE.ID
     *
     * @return the value of PUBLIC.SERVICE.ID
     *
     * @mbg.generated Wed Mar 10 20:42:44 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SERVICE.ID
     *
     * @param id the value for PUBLIC.SERVICE.ID
     *
     * @mbg.generated Wed Mar 10 20:42:44 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SERVICE.NAME
     *
     * @return the value of PUBLIC.SERVICE.NAME
     *
     * @mbg.generated Wed Mar 10 20:42:44 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SERVICE.NAME
     *
     * @param name the value for PUBLIC.SERVICE.NAME
     *
     * @mbg.generated Wed Mar 10 20:42:44 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}